### ISSUE TITLE
Create multiple thematic Stores instead of one

### ISSUE THREAD

**Issue by PJUllrich** [PJUllrich/live_ex#4]

**Comment by PJUllrich** [comment]
Once prepending/appending becomes [available](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view.ex#L89), move each Store state to its own socket assignment (e.g. `assign(socket, :store_a, %{a: 1, b: "test, ...})`)

**Comment by Maxim-Filimonov** [comment]
What kind of prepending is needed? Definitely interested in this functionality to create separate stores for different topics.

**Comment by PJUllrich** [comment]
The problem with this initially was that Phoenix LiveView didn't support `deep diffing`. So, if we were to put each store-state as a separate assign (e.g. `assign(socket, store_a: %{a: 1, b: 2}, store_b: %{c: 3, d: 4})`), and we update one of these states (e.g. `assign(socket, store_b: %{socket.assigns.store_b |  d: 5})`, LiveView would then send the entire state for `store_b` over the wire instead of only the changes (`%{d: 5}`). 

Now, however, LiveView supports [deep diffing](https://elixirforum.com/t/liveview-shallow-states-or-deep-states/31419/4) and we could leverage this to separate the store state into multiple "themes" or "topics". So, instead of storing the state as a flat map:

```elixir
@initial_store %{
  a: 1,
  b: 2
}

def init(socket) do
  assign(socket, @initial_store)
end
```
we could nest the state into topics like this:

```elixir
@initial_state %{
  topic_a: %{
    a: 1,
    b: 2
  },
  topic_b: %{
    c: 3,
    d: 4
  }
}

def init(socket) do
  assign(socket, @initial_store)
end
```

```eex
# In your template, you can then do:
<div><%= @topic_a.b %></div>
```

As of now, the above solution works and works efficiently thanks to deep diffing. However, it only separates the store into topics and not the stores. In order to do that, we'd need to:
1. Make the `live_ex_store_topic` unique per store and topic
2. Route the dispatched actions to the proper topic.
3. Call the correct mutation based on the action_type + topic.
4. Somehow offer the option to configure multiple stores with unique topics per LiveView.

I'll think about this once I've got a bit more time. In the meantime, your input would be much appreciated :)
In particular:
1. How do you image a separation? Should it be Store-based or would state-based suffice?
2. Could you maybe provide me with a concrete use-case? Then we can model the store around it.
3. If you prefer a store-based separation, do you have an idea how we could achieve this in the code?

**Comment by Maxim-Filimonov** [comment]
1) I think having a separate store is better suited. Thinking of how it's done in Redux you would essentially slice the state like a pie into separate concerns. There could be AuthStore which handles all the logic related to handling user login/logout. Even so, the state is still global, AuthStore is the one responsible for handling a specific segment of that state. So we need some way to map segments of state to specific stores. 
2) A concrete use case we have at the moment is two separate actions that don't really belong together. One action handles file uploading and relevant transformation of the state, another action handles the global switch object we have which determines what kind of form to display for a user.   
3)  For our project as we have access to the Surface context it's relatively easy to just push relevant stores into the context. 
I'm not sure about a more general approach as I don't really understand enough of live view for that. Is there a way to add like a hidden property to LV socket which would cause a re-render? I think following **Vuex** approach that would be ideal as at the moment we still need to do property drilling.

**Comment by Maxim-Filimonov** [comment]
Found this for [inspiration](https://vuex.vuejs.org/guide/modules.html)

**Comment by PJUllrich** [comment]
Hey there, thanks for the inspiration. I agree that it would be nice to have separated stores eventually. Unfortunately, this would require quite a rewrite of the library for which I don't have the time right now. 

Please feel free to use the "deep nesting" solution for now or of course send a PR my way and I'll be more than happy to review it :) 

I'll come back to this eventually for sure and here's how I'm currently planning on implementing this:
Every store would become it own [Agent](https://hexdocs.pm/elixir/1.12/Agent.html). This way, it's easy to pass around the `pid`s to the different stores and every LV can subscribe to only those stores that it needs. Also, it would enable us to have child LVs start their own store AND have access to the parent's store as well. 

So yeah, that's the plan. I'll ping you once I get to implementing it :)

**Comment by Maxim-Filimonov** [comment]
> I'll come back to this eventually for sure and here's how I'm currently planning on implementing this:
Every store would become it own Agent. This way, it's easy to pass around the pids to the different stores and every LV can subscribe to only those stores that it needs. Also, it would enable us to have child LVs start their own store AND have access to the parent's store as well.

That's a great idea. We have implemented a very simplistic version of it without using `Agent` might give you some ideas.
```
# In our store.ex
# Modules to call init on
  @init_modules %{subscribers: SubscriptionStore, account_form: LandlordFormStore}
  use SubscriptionStore
  use LandlordFormStore

 def init(socket) do
    modules_state =
      Enum.map(@init_modules, fn {k, v} ->
        {k, v.init()}
      end)
      |> Enum.into(%{})

    state = Map.merge(@initial_state, modules_state)
    init(state, socket)
  end
```
This allowed us to separate different parts of store into it's own files. Macros are not ideal solution as they make error diagnostics very tricky but it works.
```
defmodule EnaiaWeb.Stores.SubscriptionStore do
  @moduledoc """
  Handles subscription of live components and notification of subscribers
  """
  import Phoenix.LiveView, only: [update: 3, send_update: 2]

  def notify(state_slice, change, socket) do
    slice_subscribers = Map.get(socket.assigns.subscribers, state_slice)

    Enum.each(slice_subscribers, fn {module, id} ->
      params = Keyword.put([id: id], state_slice, change)
      send_update(module, params)
    end)
  end

  def init do
     # for each state slice we have a key here.
    %{
      account_form: []
    }
  end

  defmacro __using__(_opts) do
    quote do
      @doc """
      Subscribes component to specific slice update.
      Returns existing state slice state.
      """
      def subscribe(state_slice, parent_tuple, socket) do
        dispatch("new_subscriber", %{state: state_slice, parent: parent_tuple}, socket)
        Map.put(%{}, state_slice, Map.get(socket.assigns, state_slice))
      end

      def new_subscriber(%{state: state_slice, parent: parent_tuple}, socket) do
        update(socket, :subscribers, fn subscribers ->
          Map.update(subscribers, state_slice, [parent_tuple], fn current ->
            Enum.concat(current, [parent_tuple])
          end)
        end)
      end
    end
  end
end
```
LandlordForm(shorten version):
```
defmodule EnaiaWeb.Stores.LandlordFormStore do
@moduledoc """
  Handles landlord form state
  """
  alias EnaiaWeb.Stores.SubscriptionStore

 # Initial state
  def init do
    # here we return our initial store state
    %{}
  end

 defmacro __using__(_opts) do
    quote do
      import Phoenix.LiveView, only: [update: 3, assign: 2, assign: 3]

      def handle_info(%{type: "landlord_account_form_proceed"} = action, socket) do
        next_step = get_next_step(socket.assigns.account_form)

        if next_step do
          commit(action.type, action.payload, socket)
        else
          commit("landlord_account_form_save", action.payload, socket)
        end
      end

      def landlord_account_form_proceed(params, socket) do
         # updates socket state
socket =
          socket
          |> update(:account_form, fn account_form ->
            # ...
          end)

       # this is what calls send_update for that specific slice of the state
        SubscriptionStore.notify(:account_form, socket.assigns.account_form, socket)

        socket
    end
  end
```

Then in our live component, we did the following to subscribe this live component to changes:
```
socket = Surface.init(socket) |> Store.init()
# doing this will cause send_update to be called automatically on store changes to :account_form slice. 
assigns = Store.subscribe(:account_form, {__MODULE__, "landlord-form"}, socket)
```
