### ISSUE TITLE
compilation error socket/0 undefined

### ISSUE THREAD

**Issue by sfusato** [PJUllrich/live_ex#7]
I'm trying to take a look at your library, but I get a compilation error.

I copy-pasted your store example from the `How to use` section in the github Readme file.
```
== Compilation error in file lib/phoenix_web/liveviews/stores/event_store.ex ==
** (CompileError) lib/phoenix_web/liveviews/stores/event_store.ex:2: type socket/0 undefined
```
after I added the following line, it compiled:
```
@type socket :: Phoenix.LiveView.Socket.t()
```

**Comment by PJUllrich** [comment]
I'm closing this for now. Please let me know if the error still occurs.

**Comment by aikomastboom** [comment]
I just had same error / same solution
